name: BlueMap
version: "${version}"
main: de.bluecolored.bluemap.bukkit.legacy.LegacyBukkitPlugin
author: "Blue"
description: "A 3D map for Minecraft 1.5.2"
load: STARTUP
commands:
  bluemap:
    description: BlueMap commands
    usage: /bluemap
    permission: bluemap.command
permissions:
  bluemap.command:
    description: Access to BlueMap commands
    default: op
  bluemap.reload:
    description: Permission to reload BlueMap
    default: op 